### ISSUE TITLE
Chrome не работает.

### ISSUE THREAD

**Issue by denor81** [SerjoPepper/kick_sovetnik#13]
Появление самой подсказки с ценами блокирует, но при прокручивании страницы вниз - этот div элемент, как бы выплывает из под header-а. и он какой то полупрозрачный) интересный эффект. То есть этот div никуда не исчезает... а просто то ли z-index меняет, то ли еще что то... я не разбираюсь сильно. в общем для моего случая скрипт не подошел. может в обновлении что то будет.

**Comment by crypticw** [comment]
Версия хрома 55.0.2883.87 (64-bit). Скачал и подправил скрипт.
В функцию `function g(a)` 
после строки
`b.zIndex = "-9999", b.webkitTransform = b.MozTransform = b.msTransform = b.OTransform = b.transform = "translate(-9999px, -9999px)"; ` 
добавил 
`$(a).css('cssText', 'opacity:0!important; visibility:hidden!important; display:none!important;');`

Желтая полоса исчезла, но стало всплывать окошко в нижнем правом углу. Есть идеи, как убить это окно?

**Comment by crypticw** [comment]
Понял особенность. В моей дополнительной строке
`$(a).css('cssText', 'opacity:0!important; visibility:hidden!important; display:none!important;');`
нужно убрать `display:none!important;`
и окно перестанет всплывать :)
