### ISSUE TITLE
Окно справа внизу!

### ISSUE THREAD

**Issue by q10nick** [SerjoPepper/kick_sovetnik#19]
Привет! С обновлением ушла полоса советника сверху сайта... Но теперь появляется попап! Вот фото https://monosnap.com/file/z5Ve1qBWtGFlm7TZsDSLlp0J7dLiMO

**Comment by SerjoPepper** [comment]
добрый вечер, укажите пожалуйста url, на котором можно воспроизвести проблему

**Comment by hostbox2** [comment]
Подтверждаю. Вот они, окна
http://prnt.sc/e24of5
http://prnt.sc/e27e7w
В двух разных браузерах.
Причем, похоже, на пуш уведомления браузера, но я их не разрешал для расширения.

Появляется окно не сразу, заметил: открываешь страницу, переходишь в другие окна или вкладки браузера. Возвращаешься на вкладку магазина, скролишь, проходит несколько секунд - вылезает уведомление от советника.

Ссылка в картинке на страницу.

**Comment by SerjoPepper** [comment]
Попробуйте проверьте в инкогнито, там хитрая логика показа уведомлений.

**Comment by hostbox2** [comment]
В режиме инкогнито в хроме и в я.браузере не открывается окно с предложениями. Буду пробовать еще

**Comment by q10nick** [comment]
В инкогнито окна нет! может в этом спасение?)

**Comment by SerjoPepper** [comment]
Ок, закрываю тогда

**Comment by hostbox2** [comment]
Если в инкогнито режиме нет окна, то это не значит, что проблема решена. В обычном режиме окно появляется. Или я что-то не понял в логике проблемы?
