### ISSUE TITLE
Новый советник

### ISSUE THREAD

**Issue by fortuneteller** [SerjoPepper/kick_sovetnik#2]
Сегодня столкнулся с новой формой отображения - через уведомления хрома.

![_118](https://cloud.githubusercontent.com/assets/1685654/15072595/e93332b6-13a4-11e6-9fca-a001532dc2e4.png)

Не сталкивались с таким? Интересно, что можно сделать с этим

**Comment by rombell** [comment]
у других ребят прочитал, что это уведомление формируется 
средствами браузера, за пределами сайта, в случае, если 
яндекс не находит своего фрейма. Как решение предложено 
создавать собственный подставной фрейм. Я проверил - 
работает.

> Сегодня столкнулся с новой формой отображения - через 
>уведомления хрома.
> 
> ![_118](https://cloud.githubusercontent.com/assets/1685654/15072595/e93332b6-13a4-11e6-9fca-a001532dc2e4.png)
> 
> Не сталкивались с таким? Интересно, что можно сделать с 
>этим
> 
> 
> ---
> You are receiving this because you are subscribed to 
>this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SerjoPepper/kick_sovetnik/issues/2

---
С уважением - Роман Белецкий

**Comment by fortuneteller** [comment]
@rombell не могли бы вы поделиться пулл реквестом?
Заранее благодарю.

**Comment by rombell** [comment]
Извините, не имею опыта работы с гитом, поэтому не совсем 
понимаю, как это сделать.
Вот здесь ребята победили текущую версию: stopsovetnik.ru

> @rombell не могли бы вы поделиться пулл реквестом?
> Заранее благодарю.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/SerjoPepper/kick_sovetnik/issues/2#issuecomment-217509208

---
С уважением - Роман Белецкий

**Comment by AleksMaykov** [comment]
Браво Роман! Создать имитацию панели без возможности ее закрыть - чудесное решение. А если на сайте вверху баннер или панель входа? На оригинальной панели хотя бы есть кнопка закрыть эту пакость.

Скрипт с хаба работает на ура, по крайней мере на сегодня, советника просто нет.

**Comment by SerjoPepper** [comment]
@fortuneteller А можно пожалуйста страницу, где это воспроизводится.

**Comment by rombell** [comment]
Я же не настаиваю. Нас такое решение устраивает, а наверху 
мы скромно написали "На этом сайте лучшая цена"

Скрипт с хаба работает на ура, да. Но если разрешить 
пуш-уведомления в браузере, то вместо полоски этот пуш 
вылезает без вариантов.

> Браво Роман! Создать имитацию панели без возможности ее 
>закрыть - чудесное решение. А если на сайте вверху баннер 
>или панель входа? На оригинальной панели хотя бы есть 
>кнопка закрыть эту пакость.
> 
> Скрипт с хаба работает на ура, по крайней мере на 
>сегодня, советника просто нет.
> 
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/SerjoPepper/kick_sovetnik/issues/2#issuecomment-217611376

---
С уважением - Роман Белецкий

**Comment by fortuneteller** [comment]
@SerjoPepper Вот пример http://www.spellsmell.ru/women/leonard/fashion/

Google Chrome Ubuntu Версия 48.0.2564.109

Интересно еще то, что  сайт не запрашивал разрешения кидать уведомления, и, соответственно, я ничего не разрешал.

Выбран пункт "Всегда спрашивать.."
И исключения только дефолтные

![_120](https://cloud.githubusercontent.com/assets/1685654/15104467/f1b64dd4-15c9-11e6-8200-9811d1697b6c.png)

**Comment by fortuneteller** [comment]
@SerjoPepper Я пока для теста поставил решение от stopsovetnik.ru вместо вашего.

Но, конечно, лучше что-то сделать с панелью этой. Чтобы вообще ее не показывать.

**Comment by amateos** [comment]
Всем доброго дня и с днем Победы! Все проще, в скрипте SerjoPepper переделываем одну функцию remove(node)
строку "document.body.removeChild(node);" меняем на 
"node.style.cssText = 'display: none !important';"
Лучше заменить на другую функцию, например я написал функцию hide(node) и заменил в наблюдателе remove(node) на hide(node).
В итоге, желтый блок не отображается, но присутствует, что не дает скрипту пушит notification - и волки сыты и овцы целы.
С днем победы коллеги!

**Comment by fortuneteller** [comment]
@amateos Сделать попробуем, но, чувствую я это не надолго. В яндексе же не дураки сидят, проверить блок на видимость ничего им не мешает)

**Comment by amateos** [comment]
Это уже превращается в халивар :) противостояние так сказать. Вначале разработчики втыкивали скрипт через фрэймы, потом через content_scripts, даже через уведомления умудрились. Но мы тоже глупые, пока есть мочи даем отпор.

**Comment by AleksMaykov** [comment]
Вот пример что стопсоветник работает не так как задума
![default](https://cloud.githubusercontent.com/assets/19235297/15156997/4d7a44a8-16f2-11e6-9b45-3ea74f0e0765.JPG)
но.

**Comment by rombell** [comment]
Да в общем, так и задумано. Руководство одобрило, только 
надпись модифицировали: убрали "возможно".

> Вот пример что стопсоветник работает не так как задума
> ![default](https://cloud.githubusercontent.com/assets/19235297/15156997/4d7a44a8-16f2-11e6-9b45-3ea74f0e0765.JPG)
> но.
> 
> 
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/SerjoPepper/kick_sovetnik/issues/2#issuecomment-218239764

---
С уважением - Роман Белецкий

**Comment by SerjoPepper** [comment]
Пофикшено

**Comment by fortuneteller** [comment]
Спасибо!
