### ISSUE TITLE
Не работает блокировка

### ISSUE THREAD

**Issue by hostbox2** [SerjoPepper/kick_sovetnik#20]
Приветствую.

Впервые попробовал ваш метод, но он не работает.
http://prntscr.com/e1ykiw

**Comment by SerjoPepper** [comment]
Поправили, проверьте еще раз

**Comment by SerjoPepper** [comment]
Так же замечу, что для Я.Браузера подключение через внешний скрипт не работает, т.к. он блокирует загрузку это скрипта с гитхаба.
