### ISSUE TITLE
Окно справа внизу! Повтор

### ISSUE THREAD

**Issue by q10nick** [SerjoPepper/kick_sovetnik#21]
Закрыли предидущий пост не решив проблему...

Хром, инкогнито... Советник не работает, лишних окон нет... 

Хром, без инкогнито... Желтой полосы нет, но справа внизу вылезает окно от советника и предлагает товар на маркете. 

Как убрать это окно?

**Comment by hostbox2** [comment]
Кстати да, это не решение почистить куки/кеш. Посетитель этого делать не будет.
А раз воспроизводится на реальном примере в обычной повседневной работе с сайтом - значит появится у посетителя.

Но вы же заявляете, что плагин постоянно дорабатывается и надо писать вам, если появляется я.советник, а он появляется в виде дополнительного окна.

Выходит, что ваш плагин не блокирует до конца работу я.советника, оставляя лазейку для его активации.

Или надо так сразу и сказать, что вы технически не можете решить проблему с помощью js повляв на работу работу расширения в браузере. Скорее всего эти стандартные пуш окна уже невозможно заблокировать с помощью javascript.

**Comment by q10nick** [comment]
Ну я бы так автору не писал) Все же бесплатный плагин, а мы с него требуем... тем более яндекс знает про этот скрипт и пытается его обойти... А автор тратит свое время, для обновления скрипта... По этому максимум можно выкладывать информацию, что скрипт теперь не блокирует. А если надо 100% блокировку, то есть платные решения от 2000 руб/мес

**Comment by rombell** [comment]
Порекомендуйте платное решение? То, что мы пробовали, точно так же не убирает пуш. Кстати пуши у меня запрещены, но окно советника всё равно вылазит, как так?!
Что до советника, то я репортил три проблемы: полоску, пуш-окно и цифру на иконке советника в тулбаре. Предполагаю, что советник ищет, на что бы ему стриггерить, всё-таки по содержанию страницы, так что обмануть его можно. Но как? Готовы купить решение, и , думаю, не только мы.

**Comment by kerstvo** [comment]
@rombell, у вас расширение Советник или Яндекс браузер? При установке расширения оно спрашивает разрешения на показ уведомлений

![2017-01-31_09-47-54](https://cloud.githubusercontent.com/assets/1435762/22454929/66093f46-e79a-11e6-82c0-9f31eb7e1469.png)

**Comment by rombell** [comment]
У меня советник в Хроме. Да, действительно, спасибо - не знал, хромом пользуюсь только для тестов.
Тем не менее, информацию для пуша он определяет по контенту страницы. Как-то надо ему прятать

**Comment by hostbox2** [comment]
Советуют удалять schema.org теги с помощью js. Плагин скорее всего по ним ищет и отпределяет товар на странице.

Но, возможно это также не поможет, если плагин берет не текущую страницу в данный момент, а берет из кеша яндекса, где все теги schema.org есть.

**Comment by rombell** [comment]
А приведите пример таких тэгов? У нас такого вроде быть не должно, а зараза вылазит

**Comment by SerjoPepper** [comment]
если я.советник обнаружил вмешательство в свой код, он в дальнейшем будет показывать конкретно этому пользователю всплывающее окно, всплывающие окна технически заблокировать  нельзя, т.к. они доступны только из скрипта расширения. но для новых пользователей на вашем сайте я.советник показываться не будет, поэтому и требуется почистить куки/кеш или открыть в инкогнито чтобы проверить работу плагина на новых пользователях (а в случае с интернет магазинами. мы практически всегда имеем дело с новым трафиком). т.е. в данный момент это решение работает. мета-теги удалять бесполезно, т.к. советник берет информацию не только из них, и всегда есть возможность взять страницу из кеша Яндекса, а на парсить теги скриптом.

**Comment by hostbox2** [comment]
Спасибо за разъяснения, написали бы это чуток пораньше =)
