### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by ALushkov** [SerjoPepper/kick_sovetnik#22]
скрипт не работает

**Comment by SerjoPepper** [comment]
укажите пожалуйста подробности и ссылку, где это можно воспроизвести

**Comment by ALushkov** [comment]
https://www.fishers-house.ru/katushki/bezynercionnye-katushki/katushki-shimano-yaponiya/model-alivio/katushka-shimano-alivio-4000-fd.html

https://snag.gy/BIFPA3.jpg

**Comment by SerjoPepper** [comment]
у вас на сайте стоит другой скрипт для блокировки
