### ISSUE TITLE
Перестал работать блокировщик советника

### ISSUE THREAD

**Issue by 9455149** [SerjoPepper/kick_sovetnik#31]
Добрый день!
К сожалению, несколько дней назад (около недели) перестал работать скрипт, вверху страницы появляется желтая полоса советника.
Подскажите, можно ли как-то с этим справиться?

**Comment by kmvcenter** [comment]
Можно сделать так:
`  function hasSovetnikLink (node) {
  	if(node.nodeName=='#text'){
  		return false;
  	}
    return !!node.querySelector('[src*="data:image/png;base64,iVBORw0KGgoAAAA"]');
  }`

**Comment by 9455149** [comment]
Добрый день!
Подскажите, пожалуйста, куда добавить данный код? Пробовал вставить в самый конец скрипта (https://serjopepper.github.io/kick_sovetnik/dist/index.min.js), но ничего не изменилось.

**Comment by kmvcenter** [comment]
Нужно найти и заменить функцию hasSovetnikLink(), на код который я выше указал
здесь https://github.com/SerjoPepper/kick_sovetnik/blob/master/src/index.js

**Comment by 9455149** [comment]
Работает, большое спасибо))

**Comment by kmvcenter** [comment]
залил сюда https://github.com/abrkadabra/kick_sovetnik/blob/abrakadabra/dist/index.min.js
