### ISSUE TITLE
Добавление алгоритма

### ISSUE THREAD

**Issue by leotop** [SerjoPepper/kick_sovetnik#4]
Если к странице подставить 
?from=ya&productID=15367&utm_campaign=market&utm_medium=cpc&utm_source=ya.market&utm_term=15367&ymclid=65572834223300235260001

или подобный, имитируя платный переход, то советник появляться не будет.

Каким образом определяется наличие подобных меток и возможно ли параметры проверки у дополнения советника?

**Comment by SerjoPepper** [comment]
К сожалению распознавать такие метки, а тем более добавлять их ссылкам сейчас невозможно. Как минимум это стороннее вмешательство в html разметку страницы и это может много кому поломать статистику и трекинги.

**Comment by leotop** [comment]
распознавать их не нужно, достаточно любой шаблонной.
имел ввиду не добавлять их физически, а подавать на вход советника переопределяя функцию.
