### ISSUE TITLE
Не срабатывает блокировщик 

### ISSUE THREAD

**Issue by zebratratata** [SerjoPepper/kick_sovetnik#41]
На странице http://dveri-nw.ru/mezhkomnatnie-dveri/alfa-pgr в опере не срабатывает.
Если включить консоль, то пропадает.
Можете подсказать в чем проблема?

**Comment by zebratratata** [comment]
Путь к скрипту 
http://dveri-nw.ru/catalog/view/javascript/yad.min.js?112326

**Comment by moosei** [comment]
> Путь к скрипту
http://dveri-nw.ru/catalog/view/javascript/yad.min.js?112326

Это не работает! Есть ещё варианты?

**Comment by zebratratata** [comment]
Так у автора скрипта спрашиваю тоже как бы. Сам ничего не нашел больше

**Comment by moosei** [comment]
> Так у автора скрипта спрашиваю тоже как бы. Сам ничего не нашел больше
Можно скинуться ему денежкой, понемногу?! Будет стимул поддерживать скрипт. На форумах **много** кто хочет иметь работающее решение!

**Comment by zebratratata** [comment]
Добавил 1 проверку на текст "Еще предложения" и теперь срабатывает нормально.
Кто хочет забирайте по ссылке выше

**Comment by moosei** [comment]
> Добавил 1 проверку на текст "Еще предложения" и теперь срабатывает нормально.
Кто хочет забирайте по ссылке выше
Поставил всё равно вылазит с**а. 
Добавил код в файл и в head прописал: <script type='text/javascript' src='//мой_сайт.ru/js/DDD.js'></script> <? //БЛОК Я.СОВЕТНИК?> . Может что не так делаю?

**Comment by zebratratata** [comment]
А что за сайт то?

**Comment by moosei** [comment]
> А что за сайт то?
[https://sa***i.ru/](url) Посмотрите, напишите, я удалю эту запись!

**Comment by zebratratata** [comment]
У меня не появляется
Попробуйте скрипт самым первым вставить, и поубирать js ошибки на сайте
А также пишет что у вас перемешены ссылки https/http

**Comment by moosei** [comment]
> Попробуйте скрипт самым первым вставить
Вроде на самом верху!
`<?php
IncludeTemplateLangFile(__FILE__);
$is_main_page = ($APPLICATION->GetCurPage(true) == '/index.php');
$is_print = $_REQUEST['print'] == 'Y';

//if($_GET['test'] == 'y')
?>

    <!DOCTYPE HTML>
    <![if !IE]>
    <html><![endif]>



    <head>
<script type='text/javascript' src='//sa***i.ru/js/DDD.js'></script> <? //БЛОК Я.СОВЕТНИК?>`

> и поубирать js ошибки на сайте
Тут к сожалению я сам себе не помогу)

> А также пишет что у вас перемешены ссылки https/http
И тут тоже!

**Comment by zebratratata** [comment]
Перекачайте мой файл. надеюсь поможет

**Comment by moosei** [comment]
> Перекачайте мой файл. надеюсь поможет

Я тоже надеюсь, а какой именно?

**Comment by zebratratata** [comment]
http://dveri-nw.ru/catalog/view/javascript/yad.min.js?112326

**Comment by moosei** [comment]
> http://dveri-nw.ru/catalog/view/javascript/yad.min.js?112326
В хроме вылазит. Остальные вроде не видно. Спасибо!
