### ISSUE TITLE
In Yandex browser it still works

### ISSUE THREAD

**Issue by sandernik** [SerjoPepper/kick_sovetnik#6]
Thanks to the developer, very good and useful script, single working nowadays. Now, about the issue. In google Chrome and Firefox it works, but in Yandex browser it still shows adverts. Is it posible to solve this issue? Thanks in advance!

**Comment by SerjoPepper** [comment]
Здравствуйте, каким способом подключаете скрипт?

**Comment by sandernik** [comment]
Добрый день.
Добавляю перед закрытием тега </head>
<script src="//serjopepper.github.io/kick_sovetnik/dist/index.min.js" async="async"></script>

P.S.:Сайт на CMS Opencart

**Comment by SerjoPepper** [comment]
Повторите интеграцию скрипта, как указано в этом репозитории https://github.com/SerjoPepper/kick_sovetnik#Установка
Яндекс-браузер вырезает скрипты с домена serjopepper.github.io

**Comment by SerjoPepper** [comment]
Если все ок, закрываю тикет.
