### ISSUE TITLE
В последнем Я.браузере не работает

### ISSUE THREAD

**Issue by SashaTae** [SerjoPepper/kick_sovetnik#8]
В последних версиях Я.браузера перестал работать :(
На двух компах стоят версии 16.6.1.30117 и  16.6.0.8149, обновили браузер и все, никак не работает, все файлы отсюда перезалила свежие.
Собственно, страница с товаром contr.ru/musornyj-kontejner-mgb-1100.htm

**Comment by SerjoPepper** [comment]
Только что проверил, у меня не воспроизводится, версия 16.6.0

**Comment by SashaTae** [comment]
Он появляется не сразу, а спустя секунд 5.
Хотя бы не подскажете, в каком направлении может быть проблема?

**Comment by Katy007** [comment]
такая же проблема. в новом Я.Браузере советник снова жив

**Comment by bronx1** [comment]
Добрый день! Не работает в Яндексе 16.7.1.20936. На сайте установлен советник от May 25 2016 01:48:28
