### ISSUE TITLE
Зачем метрика стоит в index.min.js ??? 

### ISSUE THREAD

**Issue by starinajes** [SerjoPepper/kick_sovetnik#9]
Нахрена подключена метрика к файлу? 
https://mc.yandex.ru/watch/37415865

**Comment by bardalex** [comment]
Присоединяюсь, зачем тянется пиксель https://mc.yandex.ru/watch/37415865 ?

**Comment by Effectik** [comment]
Автор решил сдать со всеми потрохами все проекты, которые используют данный скрипт :dancing_men:

**Comment by SerjoPepper** [comment]
это нужно было чтобы оценить кол-во сайтов, использующих скрипт. вы можете убрать метрику или использовать неминифицированную версию
